-- ============================================================
-- RideFlow — SUPABASE POSTGRESQL SCHEMA + SEED
-- Generated from the supplied RideFlow project.
-- Run this file in Supabase Dashboard → SQL Editor.
-- It creates the RideFlow tables and sample data.
-- ============================================================
-- ============================================================
-- RideFlow Transport Management System — Database Schema
-- Version: 2.0 | Engine: InnoDB | Charset: utf8mb4
-- ============================================================

-- ── USERS ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             VARCHAR(120)  NOT NULL,
  email            VARCHAR(180)  NULL UNIQUE,
  phone            VARCHAR(20)   NOT NULL DEFAULT '',
  password         VARCHAR(255)  NOT NULL DEFAULT '',
  password_hash    VARCHAR(255) NULL,
  role             VARCHAR(40) NOT NULL DEFAULT 'customer',
  status           VARCHAR(40) NOT NULL DEFAULT 'pending',
  phone_verified   SMALLINT NOT NULL DEFAULT 0,
  email_verified   SMALLINT NOT NULL DEFAULT 0,
  email_token      VARCHAR(64)  NULL,
  id_type          VARCHAR(40) NULL,
  id_number        VARCHAR(120) NULL,
  selfie_url       VARCHAR(500) NULL,
  id_document_url  VARCHAR(500) NULL,
  verification_status VARCHAR(40) NOT NULL DEFAULT 'pending',
  verification_note TEXT NULL,
  reset_token      VARCHAR(64)  NULL,
  reset_expires    TIMESTAMP    NULL,
  social_provider  VARCHAR(40)  NULL,
  social_id        VARCHAR(255) NULL,
  avatar_url       VARCHAR(500) NULL,
  address          TEXT         NULL,
  created_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT uk_social UNIQUE (social_provider, social_id)
);

-- ── TRANSPORT TYPES ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS transport_types (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_name  VARCHAR(50) NOT NULL,
  icon       VARCHAR(30) NOT NULL DEFAULT 'bus',
  color      VARCHAR(10) NOT NULL DEFAULT '#ff6a00',
  is_active  SMALLINT  NOT NULL DEFAULT 1
);

-- ── VEHICLES ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS vehicles (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_id        INTEGER NOT NULL,
  vehicle_name   VARCHAR(100) NOT NULL,
  vehicle_number VARCHAR(30)  NOT NULL UNIQUE,
  capacity       INTEGER NOT NULL DEFAULT 40,
  amenities      TEXT         NULL,
  status         VARCHAR(40) NOT NULL DEFAULT 'active',
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (type_id) REFERENCES transport_types(id) ON DELETE RESTRICT
);

-- ── ROUTES ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS routes (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_id            INTEGER NOT NULL,
  route_name         VARCHAR(150) NOT NULL,
  origin             VARCHAR(100) NOT NULL,
  destination        VARCHAR(100) NOT NULL,
  distance_km        DECIMAL(8,2) NULL,
  estimated_duration VARCHAR(30)  NULL,
  status             VARCHAR(40) NOT NULL DEFAULT 'active',
  created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (type_id) REFERENCES transport_types(id) ON DELETE RESTRICT
);

-- ── ROUTE STOPS ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS route_stops (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_id   INTEGER NOT NULL,
  stop_name  VARCHAR(100) NOT NULL,
  stop_order INT          NOT NULL DEFAULT 0,
  FOREIGN KEY (route_id) REFERENCES routes(id) ON DELETE CASCADE
);

-- ── DRIVERS ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS drivers (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER NOT NULL,
  vehicle_id  INTEGER NULL,
  license_no  VARCHAR(50)  NOT NULL,
  experience  INT          NOT NULL DEFAULT 0,
  rating      DECIMAL(3,2) NOT NULL DEFAULT 5.00,
  status      VARCHAR(40) NOT NULL DEFAULT 'active',
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id)    REFERENCES users(id)    ON DELETE CASCADE,
  FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL,
CONSTRAINT uk_user UNIQUE (user_id)
);

-- ── SCHEDULES ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS schedules (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_id        INTEGER NOT NULL,
  vehicle_id      INTEGER NOT NULL,
  departure_date  DATE         NOT NULL,
  departure_time  TIME         NOT NULL,
  arrival_time    TIME         NULL,
  fare            DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  available_seats INT          NOT NULL DEFAULT 0,
  status          VARCHAR(40) NOT NULL DEFAULT 'scheduled',
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (route_id)   REFERENCES routes(id)   ON DELETE CASCADE,
  FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE RESTRICT
);

-- ── BOOKINGS ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS bookings (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          INTEGER NOT NULL,
  schedule_id      INTEGER NOT NULL,
  booking_ref      VARCHAR(20)  NOT NULL UNIQUE,
  seats_booked     INT          NOT NULL DEFAULT 1,
  total_fare       DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  passenger_name   VARCHAR(120) NOT NULL,
  passenger_phone  VARCHAR(20)  NOT NULL,
  passenger_email  VARCHAR(180) NULL,
  booking_status   VARCHAR(40) NOT NULL DEFAULT 'pending',
  payment_status   VARCHAR(40) NOT NULL DEFAULT 'unpaid',
  qr_code          TEXT         NULL,
  notes            TEXT         NULL,
  booked_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id)     REFERENCES users(id)     ON DELETE CASCADE,
  FOREIGN KEY (schedule_id) REFERENCES schedules(id) ON DELETE RESTRICT
);

-- ── PAYMENTS ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS payments (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id      INTEGER NOT NULL,
  user_id         INTEGER NOT NULL,
  gateway         VARCHAR(40) NOT NULL DEFAULT 'cash',
  amount          DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  currency        VARCHAR(5)    NOT NULL DEFAULT 'LKR',
  status          VARCHAR(40) NOT NULL DEFAULT 'pending',
  transaction_ref VARCHAR(100) NULL,
  gateway_ref     VARCHAR(200) NULL,
  gateway_data    TEXT         NULL,
  paid_at         TIMESTAMP     NULL,
  payment_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id)    REFERENCES users(id)    ON DELETE CASCADE
);

-- ── FEEDBACK ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS feedback (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NOT NULL,
  booking_id INTEGER NULL,
  rating     SMALLINT      NOT NULL DEFAULT 5,
  comment    TEXT         NULL,
  is_public  SMALLINT   NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id)    REFERENCES users(id)    ON DELETE CASCADE,
  FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE SET NULL
);

-- ── SUBSCRIPTIONS (Newsletter) ───────────────────────────────
CREATE TABLE IF NOT EXISTS subscriptions (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email        VARCHAR(180) NOT NULL UNIQUE,
  name         VARCHAR(120) NULL,
  is_active    SMALLINT   NOT NULL DEFAULT 1,
  subscribed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ── CHATBOT MESSAGES ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS chatbot_messages (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NULL,
  session_id VARCHAR(64)  NOT NULL,
  role       VARCHAR(40) NOT NULL,
  message    TEXT         NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ── CHATBOT FAQ (Admin-managed) ──────────────────────────────
CREATE TABLE IF NOT EXISTS chatbot_faq (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question   TEXT         NOT NULL,
  answer     TEXT         NOT NULL,
  keywords   VARCHAR(500) NULL,
  category   VARCHAR(60)  NULL,
  is_active  SMALLINT   NOT NULL DEFAULT 1,
  sort_order INT          NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ── NOTIFICATIONS ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS notifications (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NOT NULL,
  title      VARCHAR(200) NOT NULL,
  message    TEXT         NOT NULL,
  type       VARCHAR(40) NOT NULL DEFAULT 'system',
  is_read    SMALLINT   NOT NULL DEFAULT 0,
  link       VARCHAR(300) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ── CONTACT MESSAGES ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS contact_messages (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(120) NOT NULL,
  email      VARCHAR(180) NOT NULL,
  subject    VARCHAR(200) NOT NULL,
  message    TEXT         NOT NULL,
  is_read    SMALLINT   NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ── SITE SETTINGS ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS site_settings (
  setting_key   VARCHAR(80)  NOT NULL PRIMARY KEY,
  setting_value TEXT         NULL,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ── API TOKENS (Mobile app) ──────────────────────────────────
CREATE TABLE IF NOT EXISTS api_tokens (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NOT NULL,
  token      VARCHAR(64)  NOT NULL UNIQUE,
  expires_at TIMESTAMP     NOT NULL,
  last_used  TIMESTAMP     NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ── OTP CODES ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS otp_codes (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone      VARCHAR(20)  NOT NULL,
  code       VARCHAR(10)  NOT NULL,
  purpose    VARCHAR(30)  NOT NULL DEFAULT 'login',
  expires_at TIMESTAMP     NOT NULL,
  used       SMALLINT   NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- ── PostgreSQL indexes ───────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_phone ON users(phone);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);
CREATE INDEX IF NOT EXISTS idx_transport_types_active ON transport_types(is_active);
CREATE INDEX IF NOT EXISTS idx_vehicles_type ON vehicles(type_id);
CREATE INDEX IF NOT EXISTS idx_vehicles_status ON vehicles(status);
CREATE INDEX IF NOT EXISTS idx_routes_origin ON routes(origin);
CREATE INDEX IF NOT EXISTS idx_routes_dest ON routes(destination);
CREATE INDEX IF NOT EXISTS idx_routes_type ON routes(type_id);
CREATE INDEX IF NOT EXISTS idx_route_stops_route ON route_stops(route_id);
CREATE INDEX IF NOT EXISTS idx_drivers_vehicle ON drivers(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_schedules_route ON schedules(route_id);
CREATE INDEX IF NOT EXISTS idx_schedules_vehicle ON schedules(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_schedules_date ON schedules(departure_date);
CREATE INDEX IF NOT EXISTS idx_schedules_status ON schedules(status);
CREATE INDEX IF NOT EXISTS idx_bookings_user ON bookings(user_id);
CREATE INDEX IF NOT EXISTS idx_bookings_schedule ON bookings(schedule_id);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(booking_status);
CREATE INDEX IF NOT EXISTS idx_bookings_payment ON bookings(payment_status);
CREATE INDEX IF NOT EXISTS idx_bookings_ref ON bookings(booking_ref);
CREATE INDEX IF NOT EXISTS idx_payments_booking ON payments(booking_id);
CREATE INDEX IF NOT EXISTS idx_payments_user ON payments(user_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
CREATE INDEX IF NOT EXISTS idx_payments_gateway ON payments(gateway);
CREATE INDEX IF NOT EXISTS idx_feedback_user ON feedback(user_id);
CREATE INDEX IF NOT EXISTS idx_feedback_booking ON feedback(booking_id);
CREATE INDEX IF NOT EXISTS idx_feedback_rating ON feedback(rating);
CREATE INDEX IF NOT EXISTS idx_subscriptions_email ON subscriptions(email);
CREATE INDEX IF NOT EXISTS idx_chatbot_messages_session ON chatbot_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_chatbot_messages_user ON chatbot_messages(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications(user_id,is_read);
CREATE INDEX IF NOT EXISTS idx_contact_messages_read ON contact_messages(is_read);
CREATE INDEX IF NOT EXISTS idx_api_tokens_user ON api_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_otp_phone ON otp_codes(phone);
CREATE INDEX IF NOT EXISTS idx_otp_purpose ON otp_codes(phone,purpose);

-- ════════════════════════════════════════════════════════════
-- SAMPLE DATA
-- ════════════════════════════════════════════════════════════

-- Transport types
INSERT INTO transport_types (type_name, icon, color) VALUES
('Bus',         'bus',   '#ff6a00'),
('Train',       'train', '#38bdf8'),
('Three-Wheel', 'car',   '#22c55e'),
('Taxi',        'car',   '#f59e0b');

-- Sample users (passwords are all "password" hashed with bcrypt)
INSERT INTO users (name, email, phone, password, role, status, email_verified) VALUES
('System Admin',   'admin@rideflow.lk',  '+94771234567', '$2y$12$X0xhaZAVue0.n/Ir81bMRO1ac6JcTSSqM5eZdcLST8NPxcmvIzLgu', 'admin',    'active', 1),
('John Perera',    'john@example.com',   '+94779876543', '$2y$12$X0xhaZAVue0.n/Ir81bMRO1ac6JcTSSqM5eZdcLST8NPxcmvIzLgu', 'customer', 'active', 1),
('Sara Fernando',  'sara@example.com',   '+94712345678', '$2y$12$X0xhaZAVue0.n/Ir81bMRO1ac6JcTSSqM5eZdcLST8NPxcmvIzLgu', 'customer', 'active', 1),
('Kamal Silva',    'driver@rideflow.lk', '+94761234567', '$2y$12$X0xhaZAVue0.n/Ir81bMRO1ac6JcTSSqM5eZdcLST8NPxcmvIzLgu', 'driver',   'active', 1);

-- Vehicles
INSERT INTO vehicles (type_id, vehicle_name, vehicle_number, capacity, amenities, status) VALUES
(1, 'Express Coach A1', 'NC-1234', 45, '["AC","WiFi","USB"]', 'active'),
(1, 'Night Rider B2',   'NC-5678', 50, '["AC","USB"]',        'active'),
(2, 'Intercity Express','TR-2024', 300,'["AC","Restaurant","WiFi"]','active'),
(2, 'Rajarata Rail',    'TR-2025', 280,'["AC"]',               'active'),
(3, 'City Tuk-Tuk 1',  'WP-T001', 3,  '[]',                  'active'),
(4, 'Comfort Cab',      'WP-C001', 4,  '["AC","Water"]',      'active');

-- Routes
INSERT INTO routes (type_id, route_name, origin, destination, distance_km, estimated_duration, status) VALUES
(1,'Colombo–Kandy Express',     'Colombo',    'Kandy',       120.00,'3h 30m','active'),
(1,'Colombo–Galle Coastal',     'Colombo',    'Galle',       119.00,'2h 45m','active'),
(1,'Kandy–Jaffna Overnight',    'Kandy',      'Jaffna',      310.00,'8h 00m','active'),
(2,'Colombo–Badulla Hill Line', 'Colombo Fort','Badulla',    292.00,'9h 00m','active'),
(2,'Colombo–Kandy Intercity',   'Colombo Fort','Kandy',      120.00,'2h 30m','active'),
(3,'Colombo City Rides',        'Colombo',    'Any City Point',5.00,'15m',   'active'),
(4,'Colombo Airport Taxi',      'Colombo',    'BIA Airport',  35.00,'45m',  'active');

-- Route stops
INSERT INTO route_stops (route_id, stop_name, stop_order) VALUES
(1,'Colombo Bastian Mawatha',1),(1,'Kadawatha',2),(1,'Nittambuwa',3),(1,'Kegalle',4),(1,'Kandy',5),
(2,'Colombo Bastian Mawatha',1),(2,'Panadura',2),(2,'Kalutara',3),(2,'Hikkaduwa',4),(2,'Galle',5),
(5,'Colombo Fort',1),(5,'Kelaniya',2),(5,'Kandy',3);

-- Schedules (mix of today/future)
INSERT INTO schedules (route_id, vehicle_id, departure_date, departure_time, arrival_time, fare, available_seats, status) VALUES
(1,1,CURRENT_DATE,'06:00:00','09:30:00', 450.00, 35,'scheduled'),
(1,1,CURRENT_DATE,'10:00:00','13:30:00', 450.00, 20,'scheduled'),
(1,2,CURRENT_DATE + INTERVAL '1 day','07:00:00','10:30:00',500.00,45,'scheduled'),
(2,1,CURRENT_DATE,'07:30:00','10:15:00', 380.00, 28,'scheduled'),
(2,2,CURRENT_DATE + INTERVAL '1 day','08:00:00','10:45:00',400.00,50,'scheduled'),
(4,3,CURRENT_DATE,'05:30:00','14:30:00',1200.00,280,'scheduled'),
(5,3,CURRENT_DATE,'07:00:00','09:30:00', 350.00,280,'scheduled'),
(5,4,CURRENT_DATE,'12:00:00','14:30:00', 350.00,250,'scheduled');

-- Sample bookings
INSERT INTO bookings (user_id, schedule_id, booking_ref, seats_booked, total_fare, passenger_name, passenger_phone, passenger_email, booking_status, payment_status, booked_at) VALUES
(2,1,'RF-240001',2, 900.00,'John Perera',   '+94779876543','john@example.com','confirmed','paid',   NOW() - INTERVAL '3 days'),
(3,4,'RF-240002',1, 380.00,'Sara Fernando', '+94712345678','sara@example.com','confirmed','paid',   NOW() - INTERVAL '2 days'),
(2,6,'RF-240003',3,1050.00,'John Perera',   '+94779876543','john@example.com','confirmed','unpaid', NOW() - INTERVAL '1 day'),
(3,7,'RF-240004',1, 350.00,'Sara Fernando', '+94712345678','sara@example.com','pending',  'unpaid', NOW());

-- Sample payments
INSERT INTO payments (booking_id, user_id, gateway, amount, currency, status, transaction_ref, paid_at) VALUES
(1,2,'stripe',    900.00,'LKR','completed','TXN-STR-001',NOW() - INTERVAL '3 days'),
(2,3,'ezCash',    380.00,'LKR','completed','TXN-EZC-001',NOW() - INTERVAL '2 days');

-- Feedback
INSERT INTO feedback (user_id, booking_id, rating, comment) VALUES
(2,1,5,'Excellent service! Very comfortable and on time.'),
(3,2,4,'Good journey but bus was 10 mins late.');

-- Drivers
INSERT INTO drivers (user_id, vehicle_id, license_no, experience, rating, status) VALUES
(4,1,'B1234567',8,4.8,'active');

-- Chatbot FAQ
INSERT INTO chatbot_faq (question, answer, keywords, category, sort_order) VALUES
('How do I book a ticket?','Visit the Search page, enter your origin, destination and date, choose a trip, select seats and proceed to payment. You will receive an email confirmation.','book,booking,ticket,reserve','booking',1),
('What payment methods are accepted?','We accept Credit/Debit Cards (Stripe), PayPal, Dialog eZ Cash, Genie, Bank Transfer and Cash on Board.','payment,pay,card,ezCash,genie,PayPal','payment',2),
('Can I cancel my booking?','Yes, you can cancel from My Bookings within 2 hours of booking. Cancellations made after departure time are non-refundable.','cancel,refund,cancellation','booking',3),
('How do I get my ticket?','After payment your e-ticket is emailed to you. You can also download it from My Bookings. Show the QR code to the conductor.','ticket,download,print,qr','booking',4),
('What routes are available?','We serve Colombo–Kandy, Colombo–Galle, Kandy–Jaffna, Colombo–Badulla (train) and many city routes. Use the Search page for live availability.','route,routes,available,city','routes',5),
('How early should I arrive?','Please arrive 15 minutes before departure for buses, 30 minutes for trains.','arrive,time,departure','travel',6),
('Is Wi-Fi available on board?','AC Express coaches and intercity trains offer Wi-Fi. Check the amenities icon on the schedule listing.','wifi,internet,amenities','travel',7),
('How do I contact support?','Call +94 11 234 5678 (9am–9pm) or email support@rideflow.lk or use the Contact page.','contact,support,help,phone','support',8);

-- Subscriptions
INSERT INTO subscriptions (email, name) VALUES
('john@example.com','John Perera'),
('sara@example.com','Sara Fernando');

-- Site settings
INSERT INTO site_settings (setting_key, setting_value) VALUES
('site_name',          'RideFlow'),
('site_tagline',       'Sri Lanka Transport Booking'),
('site_email',         'info@rideflow.lk'),
('site_phone',         '+94 11 234 5678'),
('site_address',       'No.42, Galle Road, Colombo 03'),
('google_client_id',   ''),
('google_client_secret',''),
('anthropic_api_key',  ''),
('ai_enabled',         '1'),
('smtp_host',          'smtp.gmail.com'),
('smtp_port',          '587'),
('smtp_user',          ''),
('smtp_pass',          ''),
('smtp_from',          'noreply@rideflow.lk'),
('smtp_from_name',     'RideFlow'),
('stripe_pk',          ''),
('stripe_sk',          ''),
('paypal_client_id',   ''),
('sms_provider',       'demo'),
('maintenance_mode',   '0');
